version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    # this ensures a viable `mamba` is on `$PATH``
    python: mambaforge-latest
  commands:
    - mamba install -c conda-forge -c nodefaults pixi
    - pixi shell --environment docs
    - pixi run build-docs
    - rm -rf $READTHEDOCS_OUTPUT/html && mv docs/_build/html $READTHEDOCS_OUTPUT/html
sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: docs/requirements.txt
