[project]
name = "snakemake"
version = "8.29.3"
description = "Workflow management system to create reproducible and scalable data analyses"
readme = { content-type = "text/markdown", text = """
  Snakemake is a workflow management system that aims to reduce the
  complexity of creating workflows by providing a fast and comfortable
  execution environment, together with a clean and modern specification
  language in python style. Snakemake workflows are essentially Python
  scripts extended by declarative code to define rules. Rules describe
  how to create output files from input files.
""" }
requires-python = ">= 3.11"
license = { text = "MIT" }
authors = [{ name = "Johannes Köster", email = "johannes.koester@uni-due.de" }]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Environment :: Console",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: MIT License",
  "Natural Language :: English",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Topic :: Scientific/Engineering",
]

dependencies = [
  "appdirs",
  "immutables",
  "configargparse",
  "connection_pool>=0.0.3",
  "docutils",
  "gitpython",
  "humanfriendly",
  "jinja2>=3.0,<4.0",
  "jsonschema",
  "nbformat",
  "packaging",
  "psutil",
  "pulp>=2.3.1,<2.10",
  "pyyaml",
  "requests>=2.8.1,<3.0",
  "reretry",
  "smart-open>=4.0,<8.0",
  "snakemake-interface-executor-plugins>=9.3.2,<10.0",
  "snakemake-interface-common>=1.17.0,<2.0",
  "snakemake-interface-storage-plugins>=3.2.3,<4.0",
  "snakemake-interface-report-plugins>=1.1.0,<2.0.0",
  "tabulate",
  "throttler",
  "wrapt",
  "yte>=1.5.5,<2.0",
  "dpath>=2.1.6,<3.0.0",
  "conda-inject>=1.3.1,<2.0",
]

# dynamic = ["version"]

[project.urls]
Homepage = "https://snakemake.github.io"
Documentation = "https://snakemake.readthedocs.io"
Source = "https://github.com/snakemake/snakemake"

[project.optional-dependencies]
messaging = ["slack_sdk"]
pep = ["eido", "peppy"]
reports = ["pygments"]

[project.scripts]
snakemake = "snakemake.cli:main"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling", "hatch-vcs"]

[tool.hatch.build.targets.wheel]
packages = ["snakemake"]

[tool.hatch.build]
include = [
  "snakemake/**/*.css",
  "snakemake/**/*.sh",
  "snakemake/**/*.html",
  "snakemake/**/*.jinja2",
  "snakemake/**/*.js",
  "snakemake/**/*.svg",
  "snakemake/**/Snakefile",
  "snakemake/**/*.rst",
]

# [tool.hatch.version]
# source = "vcs"
# path = "snakemake/_version.py"
# [tool.hatch.build.hooks.vcs]
# version-file = "snakemake/_version.py"
# version-attr = "__version__"

artifacts = ["**/__pycache__", "**/*.py[cod]"]
